# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Affine
                                 A QGIS plugin
 This plugin transforms vector layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-04-29
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Jan Šartner, FSV ČVUT
        email                : sartnerjan@seznam.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from PyQt5.QtWidgets import QFileDialog
from qgis.core import QgsProject, QgsMapLayer, Qgis, QgsPoint, QgsPointXY, QgsGeometry, QgsFeature, QgsVectorLayer, QgsWkbTypes
from qgis._core import QgsVectorFileWriter

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .affine_dialog import AffineDialog
import os.path
import ogr
import numpy
import math

class Affine:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Affine_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Affine transformer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Affine', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/affine/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Affine transformer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Affine transformer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AffineDialog()

        # show the dialog
        self.dlg.show()

        # Clear widgets 
        self.dlg.Slayer_Cbox.clear()
        self.dlg.Source_Cbox.clear()
        self.dlg.Target_Cbox.clear()
        self.dlg.Sc_Cbox.clear()
        self.dlg.Rot_Cbox.clear()
        self.dlg.format_Cbox.clear()
        self.dlg.a_Ledit.clear()
        self.dlg.b_Ledit.clear()
        self.dlg.c_Ledit.clear()
        self.dlg.d_Ledit.clear()
        self.dlg.e_Ledit.clear()
        self.dlg.f_Ledit.clear()
        self.dlg.out_Ledit.clear()
        self.dlg.Tr_x_Ledit.clear()
        self.dlg.Tr_y_Ledit.clear()
        self.dlg.Sc_x_Ledit.clear()
        self.dlg.Sc_y_Ledit.clear()

        self.dlg.Name_Ledit.setText('New_transformed_layer')
        self.dlg.Memory_Rb.setChecked(True)
        self.dlg.Add_CheckB.setChecked(True)
        self.dlg.Overwrite_CheckB.setChecked(True)
        self.dlg.Selected_CheckB.setChecked(False)
        self.dlg.out_Ledit.setEnabled(False)
        self.dlg.out_Label.setEnabled(False)
        self.dlg.format_Label.setEnabled(False)
        self.dlg.format_Cbox.setEnabled(False)
        self.dlg.out_TButton.setEnabled(False)
        self.dlg.Overwrite_CheckB.setEnabled(False)

        # Load vector layers
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer:
                self.dlg.Slayer_Cbox.addItem(layer.name())
                self.dlg.Source_Cbox.addItem(layer.name())
                self.dlg.Target_Cbox.addItem(layer.name())
                self.dlg.Rot_Cbox.addItem(layer.name())
                self.dlg.Sc_Cbox.addItem(layer.name())
            else:
                continue
        
        self.dlg.Rot_Cbox.addItem('Origin of coor. sys.')
        self.dlg.Sc_Cbox.addItem('Origin of coor. sys.')

        self.dlg.Transform1_Push.clicked.connect(self.transform)
        self.dlg.GetP_Count.clicked.connect(self.get_params_count)
        self.dlg.GetP_Translation.clicked.connect(self.get_params_translation)
        self.dlg.GetP_Scaling.clicked.connect(self.get_params_scaling)
        self.dlg.GetP_Rotation.clicked.connect(self.get_params_rotation)
        self.dlg.out_TButton.clicked.connect(self.select_output_directory)
        self.dlg.Memory_Rb.toggled.connect(self.disable_output)
        self.dlg.Selected_CheckB.toggled.connect(self.disable_whole_layer)

        # Load output formats
        self.dlg.format_Cbox.addItem('GPKG')
        self.dlg.format_Cbox.addItem('shp')
        self.dlg.format_Cbox.addItem('GeoJSON')
        self.dlg.format_Cbox.addItem('kml')

    def disable_output(self):
        """Disables widgets for output file if 'only memory layer' is checked"""
        if self.dlg.Memory_Rb.isChecked():
            self.dlg.out_Ledit.setEnabled(False)
            self.dlg.out_Label.setEnabled(False)
            self.dlg.format_Label.setEnabled(False)
            self.dlg.format_Cbox.setEnabled(False)
            self.dlg.out_TButton.setEnabled(False)
            self.dlg.Overwrite_CheckB.setEnabled(False)
        else:
            self.dlg.out_Ledit.setEnabled(True)
            self.dlg.out_Label.setEnabled(True)
            self.dlg.format_Label.setEnabled(True)
            self.dlg.format_Cbox.setEnabled(True)
            self.dlg.out_TButton.setEnabled(True)
            self.dlg.Overwrite_CheckB.setEnabled(True)

    def disable_whole_layer(self):
        if self.dlg.Selected_CheckB.isChecked():
            self.dlg.Slayer1.setEnabled(False)
            self.dlg.Slayer_Cbox.setEnabled(False)
        else:
            self.dlg.Slayer1.setEnabled(True)
            self.dlg.Slayer_Cbox.setEnabled(True)

    def select_output_directory(self):
        """Lets user to choose output directory"""
        self.dirname = QFileDialog.getExistingDirectory(
            self.dlg, "Select directory ", os.path.expanduser("~")
        )
        self.dlg.out_Ledit.setText(self.dirname)

    def get_params_count(self):
        """Gets parameters counted from source and target single point layers"""

        source_layer_name = self.dlg.Source_Cbox.currentText()
        source_layer = QgsProject.instance().mapLayersByName(source_layer_name)[0]
        target_layer_name = self.dlg.Target_Cbox.currentText()
        target_layer = QgsProject.instance().mapLayersByName(target_layer_name)[0]
        s_type = source_layer.geometryType()
        s_wkbtype = source_layer.wkbType()
        t_type = target_layer.geometryType()
        t_wkbtype = target_layer.wkbType()
        if (s_type==QgsWkbTypes.PointGeometry) and (t_type==QgsWkbTypes.PointGeometry) and (QgsWkbTypes.isSingleType(s_wkbtype)) and (QgsWkbTypes.isSingleType(t_wkbtype)):
            s_p = []
            t_p = []
            s_ip = 0
            t_ip = 0
            for target_feature in target_layer.getFeatures():
                t_p.append(target_feature.geometry().asPoint())
                t_ip += 1
                for source_feature in source_layer.getFeatures():
                    if target_feature.id()== source_feature.id():
                        s_p.append(source_feature.geometry().asPoint())
                        s_ip += 1
                if t_ip != s_ip:
                    t_p.pop(t_ip-1)
                    t_ip -= 1

            if t_ip >= 3:
                if t_ip > 3:
                    self.iface.messageBar().pushMessage("There are more than 3 identic poins. Transformation parameters were counted from 3 points in features with the lowest ids,which are part of both layers.", level=Qgis.Warning, duration=9)
                ## /direct count\
                params = []
                params.append(((-t_p[1].x()+t_p[0].x())*(s_p[2].y()-s_p[1].y())+(t_p[2].x()-t_p[1].x())*(s_p[1].y()-s_p[0].y()))/((-s_p[1].x()+s_p[0].x())*(s_p[2].y()-s_p[1].y())+(s_p[2].x()-s_p[1].x())*(s_p[1].y()-s_p[0].y())))
                params.append(((-t_p[1].x()+t_p[0].x())*(s_p[2].x()-s_p[1].x())+(t_p[2].x()-t_p[1].x())*(s_p[1].x()-s_p[0].x()))/((-s_p[1].y()+s_p[0].y())*(s_p[2].x()-s_p[1].x())+(s_p[2].y()-s_p[1].y())*(s_p[1].x()-s_p[0].x())))
                params.append(((-t_p[1].x()*s_p[0].y()+t_p[0].x()*s_p[1].y())*(s_p[2].x()*s_p[1].y()-s_p[1].x()*s_p[2].y())+(t_p[2].x()*s_p[1].y()-t_p[1].x()*s_p[2].y())*(s_p[1].x()*s_p[0].y()-s_p[0].x()*s_p[1].y()))/((-s_p[0].y()+s_p[1].y())*(s_p[2].x()*s_p[1].y()-s_p[1].x()*s_p[2].y())+(s_p[1].y()-s_p[2].y())*(s_p[1].x()*s_p[0].y()-s_p[0].x()*s_p[1].y())))
                params.append(((-t_p[1].y()+t_p[0].y())*(s_p[2].y()-s_p[1].y())+(t_p[2].y()-t_p[1].y())*(s_p[1].y()-s_p[0].y()))/((-s_p[1].x()+s_p[0].x())*(s_p[2].y()-s_p[1].y())+(s_p[2].x()-s_p[1].x())*(s_p[1].y()-s_p[0].y())))
                params.append(((-t_p[1].y()+t_p[0].y())*(s_p[2].x()-s_p[1].x())+(t_p[2].y()-t_p[1].y())*(s_p[1].x()-s_p[0].x()))/((-s_p[1].y()+s_p[0].y())*(s_p[2].x()-s_p[1].x())+(s_p[2].y()-s_p[1].y())*(s_p[1].x()-s_p[0].x())))
                params.append(((-t_p[1].y()*s_p[0].y()+t_p[0].y()*s_p[1].y())*(s_p[2].x()*s_p[1].y()-s_p[1].x()*s_p[2].y())+(t_p[2].y()*s_p[1].y()-t_p[1].y()*s_p[2].y())*(s_p[1].x()*s_p[0].y()-s_p[0].x()*s_p[1].y()))/((-s_p[0].y()+s_p[1].y())*(s_p[2].x()*s_p[1].y()-s_p[1].x()*s_p[2].y())+(s_p[1].y()-s_p[2].y())*(s_p[1].x()*s_p[0].y()-s_p[0].x()*s_p[1].y())))

                ## It is possible to use these matrices instead of /direct count\
                #X_tr = numpy.matrix([[t_p[0].x()],[t_p[0].y()],[t_p[1].x()],[t_p[1].y()],[t_p[2].x()],[t_p[2].y()]],dtype=float)
                #X_or = numpy.matrix([[s_p[0].x(),s_p[0].y(),1,0,0,0],[0,0,0,s_p[0].x(),s_p[0].y(),1],
                #                     [s_p[1].x(),s_p[1].y(),1,0,0,0],[0,0,0,s_p[1].x(),s_p[1].y(),1],
                #                     [s_p[2].x(),s_p[2].y(),1,0,0,0],[0,0,0,s_p[2].x(),s_p[2].y(),1]],dtype=float)
                #params = (numpy.linalg.inv(X_or.transpose().dot(X_or)).dot(X_or.transpose())).dot(X_tr)

                self.dlg.a_Ledit.setText(str(float(params[0])))
                self.dlg.b_Ledit.setText(str(float(params[1])))
                self.dlg.c_Ledit.setText(str(float(params[2])))
                self.dlg.d_Ledit.setText(str(float(params[3])))
                self.dlg.e_Ledit.setText(str(float(params[4])))
                self.dlg.f_Ledit.setText(str(float(params[5])))
            else:
                self.iface.messageBar().pushMessage("There are less than 3 identic poins. Transformation isn't possible!", level=Qgis.Critical, duration=4)
        else:
            self.iface.messageBar().pushMessage("Layers for counting parameters have to be single point layers!", level=Qgis.Critical, duration=5)

    def get_params_rotation(self):
        """Gets parameters for rotation"""
        angle = float(self.dlg.Rot_ang_Ledit.text())/180*math.pi
        centre_lay_name = self.dlg.Rot_Cbox.currentText()
        if centre_lay_name == 'Origin of coor. sys.':
            centre_x = 0
            centre_y = 0
        else:
            centre_lay = QgsProject.instance().mapLayersByName(centre_lay_name)[0]
            centre_x = (centre_lay.extent().xMaximum() + centre_lay.extent().xMinimum())/2
            centre_y = (centre_lay.extent().yMaximum() + centre_lay.extent().yMinimum())/2

        self.dlg.a_Ledit.setText(str(math.cos(angle)))
        self.dlg.b_Ledit.setText(str(-math.sin(angle)))
        self.dlg.c_Ledit.setText(str(-centre_x*math.cos(angle)+centre_y*math.sin(angle)+centre_x))
        self.dlg.d_Ledit.setText(str(math.sin(angle)))
        self.dlg.e_Ledit.setText(str(math.cos(angle)))
        self.dlg.f_Ledit.setText(str(-centre_x*math.sin(angle)-centre_y*math.cos(angle)+centre_y))

    def get_params_translation(self):
        """Gets parameters for translation"""
        trans_x = float(self.dlg.Tr_x_Ledit.text())
        trans_y = float(self.dlg.Tr_y_Ledit.text())

        self.dlg.a_Ledit.setText(str(1))
        self.dlg.b_Ledit.setText(str(0))
        self.dlg.c_Ledit.setText(str(trans_x))
        self.dlg.d_Ledit.setText(str(0))
        self.dlg.e_Ledit.setText(str(1))
        self.dlg.f_Ledit.setText(str(trans_y))

    def get_params_scaling(self):
        """Gets parameters for scaling"""
        scale_x = float(self.dlg.Sc_x_Ledit.text())
        scale_y = float(self.dlg.Sc_y_Ledit.text())
        centre_lay_name = self.dlg.Sc_Cbox.currentText()
        if centre_lay_name == 'Origin of coor. sys.':
            centre_x = 0
            centre_y = 0
        else:
            centre_lay = QgsProject.instance().mapLayersByName(centre_lay_name)[0]
            centre_x = (centre_lay.extent().xMaximum() + centre_lay.extent().xMinimum())/2
            centre_y = (centre_lay.extent().yMaximum() + centre_lay.extent().yMinimum())/2

        self.dlg.a_Ledit.setText(str(scale_x))
        self.dlg.b_Ledit.setText(str(0))
        self.dlg.c_Ledit.setText(str((1-scale_x)*centre_x))
        self.dlg.d_Ledit.setText(str(0))
        self.dlg.e_Ledit.setText(str(scale_y))
        self.dlg.f_Ledit.setText(str((1-scale_y)*centre_y))

    def transform(self):
        """Transforms features in selected layer"""

        layer_name = self.dlg.Slayer_Cbox.currentText()
        layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        crs = layer.crs().authid()
        layer_features = layer.getFeatures()
        if self.dlg.Selected_CheckB.isChecked():
            layer = self.iface.activeLayer()
            crs = self.iface.activeLayer().crs().authid()
            layer_features = layer.selectedFeatures()
        out = self.dlg.out_Ledit.text()
        name = self.dlg.Name_Ledit.text()
        format = self.dlg.format_Cbox.currentText()


        if layer.geometryType() == QgsWkbTypes.PointGeometry:
            if QgsWkbTypes.isSingleType(layer.wkbType()):
                type = "point"
            else:
                type = "multipoint"
        elif layer.geometryType() == QgsWkbTypes.LineGeometry:
            if QgsWkbTypes.isSingleType(layer.wkbType()):
                type = "linestring"
            else:
                type = "multilinestring"
        elif layer.geometryType() == QgsWkbTypes.PolygonGeometry:
            if QgsWkbTypes.isSingleType(layer.wkbType()):
                type = "polygon"
            else:
                type = "multipolygon"
        else:
            type = "unknown"

        if type == "unknown":
            self.iface.messageBar().pushMessage("Unexpected type of geometry. Transformation is impossible.", level=Qgis.Critical, duration=4)
        elif (self.dlg.File_Rb.isChecked()) and (self.dlg.Overwrite_CheckB.isChecked()==False) and os.path.exists(out + '/' + name + '.'+format):
            self.iface.messageBar().pushMessage('Layer with given name already exists in output directory!', level=Qgis.Critical, duration=4)
        else:
            a = float(self.dlg.a_Ledit.text())
            b = float(self.dlg.b_Ledit.text())
            c = float(self.dlg.c_Ledit.text())
            d = float(self.dlg.d_Ledit.text())
            e = float(self.dlg.e_Ledit.text())
            f = float(self.dlg.f_Ledit.text())

            # creating layer
            layer_new = QgsVectorLayer(type + "?crs=" + crs, name, "memory")
            pr = layer_new.dataProvider()
            pr.addAttributes(layer.fields())
            layer_new.updateFields()
            
            # adding new features into new layer
            
            # Point layer
            if type == "point":
                for feature in layer_features:
                    coor = feature.geometry().asPoint()
                    coor_new_x = coor.x()*a+coor.y()*b+c
                    coor_new_y = coor.x()*d+coor.y()*e+f
                    geometry_new = QgsGeometry.fromPointXY(QgsPointXY(coor_new_x,coor_new_y))
                    
                    feature_new = QgsFeature()
                    feature_new.setGeometry(geometry_new)
                    feature_new.setAttributes(feature.attributes())
                    pr.addFeatures([feature_new])
                    layer_new.updateExtents()
            
            if type == "multipoint":
                for feature in layer_features:
                    segments_new =[]
                    coor = feature.geometry().asMultiPoint()
                    for segment in coor:
                        coor_new_x = segment.x()*a+segment.y()*b+c
                        coor_new_y = segment.x()*d+segment.y()*e+f
                        segments_new.append(QgsPointXY(coor_new_x,coor_new_y))
                    geometry_new = QgsGeometry.fromMultiPointXY(segments_new)
                    
                    feature_new = QgsFeature()
                    feature_new.setGeometry(geometry_new)
                    feature_new.setAttributes(feature.attributes())
                    pr.addFeatures([feature_new])
                    layer_new.updateExtents()
            
            # Polyline layer
            if type == "linestring":
                for feature in layer_features:
                    segments_new =[]
                    coor = feature.geometry().asPolyline()
                    for segment in coor:
                        coor_new_x = segment.x()*a+segment.y()*b+c
                        coor_new_y = segment.x()*d+segment.y()*e+f
                        segments_new.append(QgsPointXY(coor_new_x,coor_new_y))
                    geometry_new = QgsGeometry.fromPolylineXY(segments_new)
                    
                    feature_new = QgsFeature()
                    feature_new.setGeometry(geometry_new)
                    feature_new.setAttributes(feature.attributes())
                    pr.addFeatures([feature_new])
                    layer_new.updateExtents()
            
            if type == "multilinestring":
                for feature in layer_features:
                    segments1_new = []
                    coor = feature.geometry().asMultiPolyline()
                    for segment1 in coor:
                        segments2_new = []
                        for segment2 in segment1:
                            coor_new_x = segment2.x()*a+segment2.y()*b+c
                            coor_new_y = segment2.x()*d+segment2.y()*e+f
                            segments2_new.append(QgsPointXY(coor_new_x,coor_new_y))
                        segments1_new.append(segments2_new)
                    geometry_new = QgsGeometry.fromMultiPolylineXY(segments1_new)
                    
                    feature_new = QgsFeature()
                    feature_new.setGeometry(geometry_new)
                    feature_new.setAttributes(feature.attributes())
                    pr.addFeatures([feature_new])
                    layer_new.updateExtents()
            
            # Polygon layer
            if type == "polygon":
                for feature in layer_features:
                    segments1_new = []
                    coor = feature.geometry().asPolygon()
                    for segment1 in coor:
                        segments2_new = []
                        for segment2 in segment1:
                            coor_new_x = segment2.x()*a+segment2.y()*b+c
                            coor_new_y = segment2.x()*d+segment2.y()*e+f
                            segments2_new.append(QgsPointXY(coor_new_x,coor_new_y))
                        segments1_new.append(segments2_new)
                    geometry_new = QgsGeometry.fromPolygonXY(segments1_new)
                    
                    feature_new = QgsFeature()
                    feature_new.setGeometry(geometry_new)
                    feature_new.setAttributes(feature.attributes())
                    pr.addFeatures([feature_new])
                    layer_new.updateExtents()
            
            if type == "multipolygon":
                for feature in layer_features:
                    segments1_new = []
                    coor = feature.geometry().asMultiPolygon()
                    for segment1 in coor:
                        segments2_new = []
                        for segment2 in segment1:
                            segments3_new = []
                            for segment3 in segment2:
                                coor_new_x = segment3.x()*a+segment3.y()*b+c
                                coor_new_y = segment3.x()*d+segment3.y()*e+f
                                segments3_new.append(QgsPointXY(coor_new_x,coor_new_y))
                            segments2_new.append(segments3_new)
                        segments1_new.append(segments2_new)
                    geometry_new = QgsGeometry.fromMultiPolygonXY(segments1_new)
                    
                    feature_new = QgsFeature()
                    feature_new.setGeometry(geometry_new)
                    feature_new.setAttributes(feature.attributes())
                    pr.addFeatures([feature_new])
                    layer_new.updateExtents()
            
            if self.dlg.Memory_Rb.isChecked():
                self.iface.messageBar().pushMessage('Memory layer created.', level=Qgis.Success, duration=3)
                if self.dlg.Add_CheckB.isChecked():
                    QgsProject.instance().addMapLayer(layer_new)
                    self.dlg.Slayer_Cbox.addItem(layer_new.name())
                    self.dlg.Source_Cbox.addItem(layer_new.name())
                    self.dlg.Target_Cbox.addItem(layer_new.name())
                    self.dlg.Rot_Cbox.addItem(layer_new.name())
                    self.dlg.Sc_Cbox.addItem(layer_new.name())
            
            # creating file with new layer
            if self.dlg.File_Rb.isChecked():
                if(format == 'GPKG'):
                    error = QgsVectorFileWriter.writeAsVectorFormat(layer_new, out + '/' + name,"")
                if(format == 'shp'):
                    error = QgsVectorFileWriter.writeAsVectorFormat(layer_new, out + '/' + name,"UTF-8",driverName="ESRI Shapefile")
                if(format == 'GeoJSON'):
                    error = QgsVectorFileWriter.writeAsVectorFormat(layer_new, out + '/' + name,"UTF-8",driverName="GeoJSON")
                if(format == 'kml'):
                    error = QgsVectorFileWriter.writeAsVectorFormat(layer_new, out + '/' + name,"UTF-8",driverName="KML")
                
                if error[0] == QgsVectorFileWriter.NoError:
                    self.iface.messageBar().pushMessage('File created.', level=Qgis.Success, duration=3)
                else:
                    self.iface.messageBar().pushMessage('File not created!', level=Qgis.Critical, duration=4)
                
                if self.dlg.Add_CheckB.isChecked():
                    QgsProject.instance().addMapLayer(QgsVectorLayer(path = out + '/' + name + '.' + format,baseName = name))
                    self.dlg.Slayer_Cbox.addItem(layer_new.name())
                    self.dlg.Source_Cbox.addItem(layer_new.name())
                    self.dlg.Target_Cbox.addItem(layer_new.name())
                    self.dlg.Rot_Cbox.addItem(layer_new.name())
                    self.dlg.Sc_Cbox.addItem(layer_new.name())