# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Affine
                                 A QGIS plugin
 This plugin transforms vector layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-04-29
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Jan Šartner, FSV ČVUT
        email                : sartnerjan@seznam.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction
from PyQt5.QtWidgets import QFileDialog
from qgis.core import QgsProject, QgsMapLayer, Qgis, QgsPointXY, QgsGeometry, QgsFeature, QgsVectorLayer
from qgis._core import QgsVectorFileWriter

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .affine_dialog import AffineDialog
import os.path


class Affine:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Affine_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Affine transformer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Affine', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/affine/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Affine transformer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Affine transformer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AffineDialog()

        # show the dialog
        self.dlg.show()

        # Clear widgets 
        self.dlg.Slayer_Cbox.clear()
        self.dlg.a_Ledit.clear()
        self.dlg.b_Ledit.clear()
        self.dlg.c_Ledit.clear()
        self.dlg.d_Ledit.clear()
        self.dlg.e_Ledit.clear()
        self.dlg.f_Ledit.clear()
        self.dlg.out_Ledit.clear()

        #       DELETE     !!!!   #{ !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        self.dlg.a_Ledit.setText('1')
        self.dlg.b_Ledit.setText('0')
        self.dlg.c_Ledit.setText('1')
        self.dlg.d_Ledit.setText('0')
        self.dlg.e_Ledit.setText('1')
        self.dlg.f_Ledit.setText('1')
        self.dlg.out_Ledit.setText('D:/Dokumenty/škola/2018-19/2. semestr/Free software GIS/QGIS_Plugins/affine_out')
        #       DELETE     !!!!   #}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        # Load vector layers
        for layer in QgsProject.instance().mapLayers().values():
            if layer.type() == QgsMapLayer.VectorLayer:
                self.dlg.Slayer_Cbox.addItem(layer.name())
            else:
                continue

        self.dlg.Transform1_Push.clicked.connect(self.transform)
        self.dlg.out_TButton.clicked.connect(self.select_output_directory)

        # Load output formats
        self.dlg.format_Cbox.addItem('GPKG')
        self.dlg.format_Cbox.addItem('shp')

    def select_output_directory(self):
        """Lets user to choose output directory"""
        self.dirname = QFileDialog.getExistingDirectory(
            self.dlg, "Select directory ", os.path.expanduser("~")
        )
        self.dlg.out_Ledit.setText(self.dirname)

    def transform(self):
        """Transforms features in selected layer"""

        a = float(self.dlg.a_Ledit.text())
        b = float(self.dlg.b_Ledit.text())
        c = float(self.dlg.c_Ledit.text())
        d = float(self.dlg.d_Ledit.text())
        e = float(self.dlg.e_Ledit.text())
        f = float(self.dlg.f_Ledit.text())
        out = self.dlg.out_Ledit.text()
        format = self.dlg.format_Cbox.currentText()

        layer_name = self.dlg.Slayer_Cbox.currentText()
        layer = QgsProject.instance().mapLayersByName(layer_name)[0]
        crs = layer.crs().authid()

        layer_new = QgsVectorLayer("point?crs=" + crs, "temporary_layer", "memory")
        pr = layer_new.dataProvider()
        pr.addAttributes(layer.fields())
        layer_new.updateFields()

        for feature in layer.getFeatures():
            id = feature.id()
            coor = feature.geometry().asPoint()
            coor_new_x = coor[1]*a+coor[0]*b+c
            coor_new_y = coor[1]*d+coor[0]*e+f
            coor_new_qg = QgsGeometry.fromPointXY(QgsPointXY(coor_new_y,coor_new_x))
            feature_new = QgsFeature()
            feature_new.setGeometry(coor_new_qg)
            feature_new.setAttributes(feature.attributes())
            pr.addFeatures([feature_new])
            layer_new.updateExtents()

        if(format == 'GPKG'):
           QgsVectorFileWriter.writeAsVectorFormat(layer_new, out + '/' + layer_name + '_transformed',"")
        if(format == 'shp'):
           QgsVectorFileWriter.writeAsVectorFormat(layer_new, out + '/' + layer_name + '_transformed',"UTF-8",driverName="ESRI Shapefile")
